"""clean init after feature removal

Revision ID: dd6e39a2c556
Revises:
Create Date: 2026-09-09 13:30:21.926513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = 'dd6e39a2c556'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'access_grant',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('resource_type', sa.Text(), nullable=False),
        sa.Column('resource_id', sa.Text(), nullable=False),
        sa.Column('principal_type', sa.Text(), nullable=False),
        sa.Column('principal_id', sa.Text(), nullable=False),
        sa.Column('permission', sa.Text(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'resource_type', 'resource_id', 'principal_type', 'principal_id', 'permission', name='uq_access_grant_grant'
        ),
    )
    op.create_table(
        'api_key',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('expires_at', sa.BigInteger(), nullable=True),
        sa.Column('last_used_at', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('key'),
    )
    op.create_table(
        'auth',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'chat',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('chat', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('share_id', sa.Text(), nullable=True),
        sa.Column('archived', sa.Boolean(), nullable=True),
        sa.Column('pinned', sa.Boolean(), nullable=True),
        sa.Column('meta', sa.JSON(), server_default='{}', nullable=True),
        sa.Column('variables', sa.JSON(), nullable=True),
        sa.Column('folder_id', sa.Text(), nullable=True),
        sa.Column('tasks', sa.JSON(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('current_message_id', sa.Text(), nullable=True),
        sa.Column('last_read_at', sa.BigInteger(), nullable=True),
        sa.Column('timer_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('share_id'),
    )
    op.create_index('folder_id_idx', 'chat', ['folder_id'], unique=False)
    op.create_index('folder_id_user_id_idx', 'chat', ['folder_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_chat_created_at'), 'chat', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_updated_at'), 'chat', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_user_id'), 'chat', ['user_id'], unique=False)
    op.create_index(
        'timer_at_idx',
        'chat',
        ['timer_at'],
        unique=False,
        sqlite_where=sa.text('timer_at IS NOT NULL'),
        postgresql_where=sa.text('timer_at IS NOT NULL'),
    )
    op.create_index('updated_at_user_id_idx', 'chat', ['updated_at', 'user_id'], unique=False)
    op.create_index('user_id_archived_idx', 'chat', ['user_id', 'archived'], unique=False)
    op.create_index(
        'user_id_folder_unread_idx',
        'chat',
        ['user_id', 'folder_id', 'archived', 'updated_at', 'last_read_at', 'id'],
        unique=False,
    )
    op.create_index('user_id_pinned_idx', 'chat', ['user_id', 'pinned'], unique=False)
    op.create_index(
        'user_id_timer_at_idx',
        'chat',
        ['user_id', 'timer_at'],
        unique=False,
        sqlite_where=sa.text('timer_at IS NOT NULL'),
        postgresql_where=sa.text('timer_at IS NOT NULL'),
    )
    op.create_index(
        'user_id_updated_at_id_idx', 'chat', ['user_id', sa.literal_column('updated_at DESC'), 'id'], unique=False
    )
    op.create_table(
        'config',
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('key'),
    )
    op.create_table(
        'file',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('hash', sa.Text(), nullable=True),
        sa.Column('filename', sa.Text(), nullable=True),
        sa.Column('path', sa.Text(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_index(op.f('ix_file_created_at'), 'file', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_user_id'), 'file', ['user_id'], unique=False)
    op.create_table(
        'folder',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('parent_id', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('items', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('is_expanded', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'function',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('type', sa.Text(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('meta', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('valves', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_global', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_index('is_global_idx', 'function', ['is_global'], unique=False)
    op.create_index(op.f('ix_function_user_id'), 'function', ['user_id'], unique=False)
    op.create_table(
        'group',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'model',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('base_model_id', sa.Text(), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('params', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('meta', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'oauth_session',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('provider', sa.Text(), nullable=False),
        sa.Column('token', sa.Text(), nullable=False),
        sa.Column('expires_at', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_index('idx_oauth_session_expires_at', 'oauth_session', ['expires_at'], unique=False)
    op.create_index('idx_oauth_session_user_id', 'oauth_session', ['user_id'], unique=False)
    op.create_index('idx_oauth_session_user_provider', 'oauth_session', ['user_id', 'provider'], unique=False)
    op.create_table(
        'prompt_history',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('prompt_id', sa.Text(), nullable=False),
        sa.Column('parent_id', sa.Text(), nullable=True),
        sa.Column('snapshot', sa.JSON(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('commit_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_prompt_history_prompt_id'), 'prompt_history', ['prompt_id'], unique=False)
    op.create_table(
        'tag',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id', 'user_id', name='pk_id_user_id'),
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_table(
        'tool',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('name', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('specs', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('meta', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('valves', open_webui.internal.db.JSONField(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_index(op.f('ix_tool_created_at'), 'tool', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_user_id'), 'tool', ['user_id'], unique=False)
    op.create_table(
        'user',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('profile_image_url', sa.Text(), nullable=True),
        sa.Column('profile_banner_image_url', sa.Text(), nullable=True),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('gender', sa.Text(), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('timezone', sa.String(), nullable=True),
        sa.Column('presence_state', sa.String(), nullable=True),
        sa.Column('status_emoji', sa.String(), nullable=True),
        sa.Column('status_message', sa.Text(), nullable=True),
        sa.Column('status_expires_at', sa.BigInteger(), nullable=True),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('variables', sa.JSON(), nullable=True),
        sa.Column('settings', sa.JSON(), nullable=True),
        sa.Column('oauth', sa.JSON(), nullable=True),
        sa.Column('scim', sa.JSON(), nullable=True),
        sa.Column('last_active_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'chat_file',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('chat_id', sa.Text(), nullable=False),
        sa.Column('message_id', sa.Text(), nullable=True),
        sa.Column('file_id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chat_id', 'file_id', name='uq_chat_file_chat_file'),
        sa.UniqueConstraint('id'),
    )
    op.create_table(
        'chat_message',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('chat_id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('role', sa.Text(), nullable=False),
        sa.Column('parent_id', sa.Text(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('output', sa.JSON(), nullable=True),
        sa.Column('model_id', sa.Text(), nullable=True),
        sa.Column('files', sa.JSON(), nullable=True),
        sa.Column('sources', sa.JSON(), nullable=True),
        sa.Column('embeds', sa.JSON(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('done', sa.Boolean(), nullable=True),
        sa.Column('status_history', sa.JSON(), nullable=True),
        sa.Column('error', sa.JSON(), nullable=True),
        sa.Column('usage', sa.JSON(), nullable=True),
        sa.Column('context_summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('chat_message_chat_parent_idx', 'chat_message', ['chat_id', 'parent_id'], unique=False)
    op.create_index('chat_message_chat_role_done_idx', 'chat_message', ['chat_id', 'role', 'done'], unique=False)
    op.create_index('chat_message_model_created_idx', 'chat_message', ['model_id', 'created_at'], unique=False)
    op.create_index('chat_message_user_created_idx', 'chat_message', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_chat_id'), 'chat_message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_message_created_at'), 'chat_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_model_id'), 'chat_message', ['model_id'], unique=False)
    op.create_index(op.f('ix_chat_message_user_id'), 'chat_message', ['user_id'], unique=False)
    op.create_table(
        'group_member',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('group_id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    op.create_index('ix_group_member_user_id_group_id', 'group_member', ['user_id', 'group_id'], unique=False)
    op.create_table(
        'shared_chat',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('chat_id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('chat', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_chat')
    op.drop_index('ix_group_member_user_id_group_id', table_name='group_member')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_chat_message_user_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_model_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_created_at'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_chat_id'), table_name='chat_message')
    op.drop_index('chat_message_user_created_idx', table_name='chat_message')
    op.drop_index('chat_message_model_created_idx', table_name='chat_message')
    op.drop_index('chat_message_chat_role_done_idx', table_name='chat_message')
    op.drop_index('chat_message_chat_parent_idx', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_file')
    op.drop_table('user')
    op.drop_index(op.f('ix_tool_user_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_created_at'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_prompt_history_prompt_id'), table_name='prompt_history')
    op.drop_table('prompt_history')
    op.drop_index('idx_oauth_session_user_provider', table_name='oauth_session')
    op.drop_index('idx_oauth_session_user_id', table_name='oauth_session')
    op.drop_index('idx_oauth_session_expires_at', table_name='oauth_session')
    op.drop_table('oauth_session')
    op.drop_table('model')
    op.drop_table('group')
    op.drop_index(op.f('ix_function_user_id'), table_name='function')
    op.drop_index('is_global_idx', table_name='function')
    op.drop_table('function')
    op.drop_table('folder')
    op.drop_index(op.f('ix_file_user_id'), table_name='file')
    op.drop_index(op.f('ix_file_created_at'), table_name='file')
    op.drop_table('file')
    op.drop_table('config')
    op.drop_index('user_id_updated_at_id_idx', table_name='chat')
    op.drop_index(
        'user_id_timer_at_idx',
        table_name='chat',
        sqlite_where=sa.text('timer_at IS NOT NULL'),
        postgresql_where=sa.text('timer_at IS NOT NULL'),
    )
    op.drop_index('user_id_pinned_idx', table_name='chat')
    op.drop_index('user_id_folder_unread_idx', table_name='chat')
    op.drop_index('user_id_archived_idx', table_name='chat')
    op.drop_index('updated_at_user_id_idx', table_name='chat')
    op.drop_index(
        'timer_at_idx',
        table_name='chat',
        sqlite_where=sa.text('timer_at IS NOT NULL'),
        postgresql_where=sa.text('timer_at IS NOT NULL'),
    )
    op.drop_index(op.f('ix_chat_user_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_updated_at'), table_name='chat')
    op.drop_index(op.f('ix_chat_created_at'), table_name='chat')
    op.drop_index('folder_id_user_id_idx', table_name='chat')
    op.drop_index('folder_id_idx', table_name='chat')
    op.drop_table('chat')
    op.drop_table('auth')
    op.drop_table('api_key')
    op.drop_table('access_grant')
    # ### end Alembic commands ###
